### PR TITLE
feat: proxy sslmode parameter to Sequel

### PR DESCRIPTION
**Pull request by FrankZZ**
I've made this PR to enable the use of SSL when connecting to a Postgres database server. Also updated the README.md.

### CODE REVIEW

**Comment by bethesque** [comment]
Thanks. I would prefer `PACT_BROKER_DATABASE_SSL_MODE` I think. Is 'prefer' is backwards compatible?

**Comment by bethesque** [comment]
Oh, I see, `SSLMODE` is the postgres name for it.

**Comment by bethesque** [comment]
Ok, I'm going to merge it, but I'll make some changes, because I don't want to send the SSLMODE to non-postgres connections.

**Comment by bethesque** [comment]
Released in 2.42.0-1

**Comment by FrankZZ** [comment]
@bethesque Thanks! Regarding your comment about `prefer` being backward compatible: since it "prefers" SSL it should still run with non-ssl connections. Otherwise it would be `require`

**Pull request merged**
