### PR TITLE
chore: update workflow to point to the .github repo

### PR DESCRIPTION
**Pull request by Ilia**
This updates the comment create trigger and adds a better comment on the issue which has more meaningful comment when Jira ticket is created and is aligned with other triggers.

### CODE REVIEW

**Review by Inksprout — APPROVED** [review]

**Comment by TimothyJones** [comment]
I don't think this belongs in the open source project.

**Comment by TimothyJones** [comment]
(unless you are planning to make the jira available to all)

**Comment by Ilia** [comment]
Hey @TimothyJones I do understand the reservation of having this here, that said, it will help the PactFlow/SmartBear team with supporting this repository by syncing the work from here to our internal Jira/work management tool, see here for information that @bethesque provided when we originally added it: 

Screen Shot 2023-02-09 at 3 16 30 pm

**Comment by bethesque** [comment]
Thanks Ilia!

**Comment by TimothyJones** [comment]
Ok. I'd like to lodge my complaint about this - as it reduces visibility for issue progress in the _actual_ open source project.

I would have commented this on the heads up (that I assumed I just missed), but as a directly relevant example of the reduced visibility for people outside smartbear, here's what I found when I searched for the screenshot you posted:

Screen Shot 2023-02-09 at 3 54 18 pm

Please remember that Pact is not owned by Smartbear.

**Comment by mefellows** [comment]
> I would have commented this on the heads up (that I assumed I just missed), but as a directly relevant example of the reduced visibility for people outside smartbear, here's what I found when I searched for the screenshot you posted:

Ah, this was shared in the #maintainers channel Tim. The plan is to put more resources behind the OSS ecosystem, and just as importantly, more clarity on how we plan to support it. To do this we need to improve the visibility within SmartBear of the work we are doing. There will be further communication on what this means in practice, including in more public spaces (including #general, our docs and these repositories).

> Ok. I'd like to lodge my complaint about this - as it reduces visibility for issue progress in the actual open source project.

Noted, but I do think it's misguided. Think of the Jira issue as a pointer to the public GitHub item (the source of truth), where all of the discussion on the issue, implementation etc. will be. The Jira issue is simply for accounting and planning within the SmartBear engineering environment.

**Comment by TimothyJones** [comment]
All of the above sounds reasonable, but I’m sure you can appreciate that without that context (and indeed, without any way to access that context except complaining about it directly), it just feels like “this issue has been moved private”, which is not very open source.

I’m pleased to hear that’s not what it’s supposed to mean, of course.

Perhaps the auto message should be updated to say something like “this issue has been flagged in SmartBear JIRA for internal visibility, all discussion should continue here on GitHub” so that it’s clearer.

**Comment by mefellows** [comment]
> All of the above sounds reasonable, but I’m sure you can appreciate that without that context (and indeed, without any way to access that context except complaining about it directly), it just feels like “this issue has been moved private”, which is not very open source.

Absolutely, and apologies for the confusion. 

> I’m pleased to hear that’s not what it’s supposed to mean, of course.
> 
> Perhaps the auto message should be updated to say something like “this issue has been flagged in SmartBear JIRA for internal visibility, all discussion should continue here on GitHub” so that it’s clearer.

We've been debating the wording here a bit, but yes something to that effect is what is needed. 

I think this change just reduces the duplication of the configuration across repos to use a shared config, but we'll still need to update the auto-responses here: https://github.com/pact-foundation/.github/blob/master/.github/workflows/

**Pull request merged**
