### PR TITLE
chore/multistage docker build

### PR DESCRIPTION
**Pull request by elliottmurray**

### CODE REVIEW

**Comment by elliottmurray** [comment]
@bethesque @k-ong I was bored so had a go at this. It is a little smaller locally for me but I couldn't get squash to work. I took the sqllite and mario installs out (they may be needed) There are some optimizations but up to you if it's useful or not (you can trash if you like!)

**Comment by bethesque** [comment]
Mariadb is used for MySQL, and we need Sqlite for demo purposes. But if you can add them back in, i'll happily accept the PR.

**Comment by k-ong** [comment]
yup, other than re-adding mariadb and sqlite dev libraries back, this LGTM.

**Comment by elliottmurray** [comment]
Done. I dry-ed it up a little as well.

**Comment by bethesque** [comment]
Sorry, I forgot about this. Just did a build and pushed a test image. Unfortunately it is larger than the current image 🤔 

Screen Shot 2020-11-14 at 10 32 05 am

**Comment by cfmack** [comment]
Out of curiosity, if you are focused on container size, I have successfully used the experimental squash feature in Docker.  https://github.com/docker/docker-ce/blob/master/components/cli/docs/reference/commandline/build.md#squash-an-images-layers---squash-experimental-only

It greatly shrunk our containers prior to going through a Stage environment for testing.

**Comment by bethesque** [comment]
I think Elliot tried it, but it wasn't working/enabled on either his local machine or the remote build. If Github Actions supports it though, we should be able to give it a go, because that's where we publish from.

**Comment by bethesque** [comment]
Notes for me to follow up on: https://github.com/actions/virtual-environments/issues/368

**Comment by bethesque** [comment]
Closing, but thanks for the work on this Elliot.

**Pull request closed without merging**
